version: '3'
services:
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    networks: 
      - api-env
  movies_api:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/src/
      - nodemodules:/src/node_modules
    networks: 
      - api-env
    links:
      - mongodb
    depends_on: 
      - mongodb

networks:
  api-env:
    driver: bridge

volumes:
  nodemodules: {}
