version: '3'
services:
  # postgres:
  #   image: postgres
  #   environment: 
  #     POSTGRES_PASSWORD: "iliamovies"
  #   ports:
  #     - "5432:5432"
  #   networks: 
  #     - api-env
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    networks: 
      - api-env
  movies_api:
    build: .
    command: npm run:watch
    ports:
      - "3000:3000"
    volumes:
      - .:/src/
      - nodemodules:/src/nodemodules
    networks: 
      - api-env
    links:
      - mongodb
    depends_on: 
      - mongodb

networks:
  api-env:
    driver: bridge

volumes:
  nodemodules: {}
